botToken:
ownerId: 
infoChannel: general
roleToCommandPermissions:
  '@everyone':
  - help
  - guildstats
  'the client':
  - help
  - lastseen
  - logout
  - save
  - stats
  - textstats
  - voicestats
  'owner':
  - help
  - logout
  - save
  - stats
  - guildstats
  - textstats
  - voicestats
dataDirectoryPath: ../
statsSavePeriodMinutes: 10
jvmMetricsEnabled: True
graphiteHost: carbon.dmz.unrecoverable.org
graphiteRate: 10
graphiteRateUnit: SECONDS
#channelReplyWhitelist: