botToken: 
ownerId: 
commandPrefix: $
infoChannel: 
roleToCommandPermissions:
  '@everyone':
  - help
  'owner':
  - help
  - logout
  - lastseen
  - guildstats
  - save
  - stats
  - guildstats
  - textstats
  - voicestats
dataDirectoryPath: ../bot-data
statsSavePeriodMinutes: 5
jvmMetricsEnabled: True
graphiteHost: 
graphiteRate: 10
graphiteRateUnit: SECONDS
#channelReplyWhitelist: