botToken:
roleToCommandPermissions:
  '@everyone':
  - help
  - guildstats
  'the client':
  - help
  - lastseen
  - logout
  - save
  - stats
  'owner':
  - help
  - logout
  - save
  - guildstats
dataDirectoryPath: ../
statsSavePeriodMinutes: 10
channelReplyWhitelist: